name: infotainment_demo
description: Desktop demonstration host for the Veloce Lua plugin runtime.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.6.0
  veloce_lua_core:
    path: ../../packages/veloce_lua_core
  veloce_lua_flutter:
    path: ../../packages/veloce_lua_flutter
  veloce_lua_native:
    path: ../../packages/veloce_lua_native

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
